[package]
name = "subnet"
version = "0.1.0"
authors = ["2mill <yannick.dorn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
